# Generated by Django 5.0.2 on 2024-03-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Catagory',
            fields=[
                ('Product_Catagory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Catagory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_brand', models.CharField(max_length=100)),
                ('product_catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_catagory')),
            ],
        ),
    ]
